parameters:
    mongo_host: mongo

doctrine_mongodb:
    default_connection: default
    default_document_manager: default
    default_database: pipes-connectors
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
        metrics:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    document_managers:
        default:
            mappings:
                ApplicationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.project_dir%/vendor/hanaboso/pipes-php-sdk/src/Application/Document"
                    prefix: Hanaboso\PipesPhpSdk\Application\Document
        metrics:
            connection: metrics
            database: metrics