services:
    _defaults:
        public: '%public.services%'

    hbpf.application.airtable:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Airtable\AirtableApplication

    hbpf.connector.airtable_new_record:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Airtable\Connector\AirtableNewRecordConnector
        calls:
            - setApplication : ['@hbpf.application.airtable']
            - setDb : ['@doctrine_mongodb.odm.default_document_manager']
            - setSender : ['@hbpf.transport.curl_manager']

