services:
    _defaults:
        public: '%public.services%'

    hbpf.application.airtable:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Airtable\AirtableApplication

    hbpf.connector.airtable_new_record:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Airtable\Connector\AirtableNewRecordConnector
        calls:
            - setApplication : ['@hbpf.application.airtable']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

