services:
    _defaults:
        public: '%public.services%'

    hbpf.application.s3:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\S3Application
        arguments:

    hbpf.connector.s3-create-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\S3CreateObjectConnector
        calls:
            -   setApplication: [ '@hbpf.application.s3' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.s3-get-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\S3GetObjectConnector
        calls:
            -   setApplication: [ '@hbpf.application.s3' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.s3-delete-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\S3DeleteObjectConnector
        calls:
            -   setApplication: [ '@hbpf.application.s3' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.application.redshift:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\Redshift\RedshiftApplication
        arguments:

    hbpf.connector.redshift-execute-query:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\Redshift\Connector\RedshiftExecuteQueryConnector
        calls:
            -   setApplication: [ '@hbpf.application.redshift' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]
