services:
    _defaults:
        public: '%public.services%'

    hbpf.application.fakturoid:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\FakturoidApplication

    hbpf.connector.fakturoid.get-account-detail:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidGetAccountDetailConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - [ 'setApplication', [ '@hbpf.application.fakturoid' ] ]

    hbpf.connector.fakturoid.create-new-invoice:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidCreateNewInvoiceConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - [ 'setApplication', [ '@hbpf.application.fakturoid' ] ]

    hbpf.connector.fakturoid.create-new-subject:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidCreateNewSubjectConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - [ 'setApplication', [ '@hbpf.application.fakturoid' ] ]