services:
    _defaults:
        public: '%public.services%'

    hbpf.application.fakturoid:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\FakturoidApplication

    hbpf.connector.fakturoid.get-account-detail:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidGetAccountDetailConnector
        calls:
            -   setApplication: [ '@hbpf.application.fakturoid' ]
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]

    hbpf.connector.fakturoid.create-new-invoice:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidCreateNewInvoiceConnector
        calls:
            -   setApplication: [ '@hbpf.application.fakturoid' ]
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]

    hbpf.connector.fakturoid.create-new-subject:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Fakturoid\Connector\FakturoidCreateNewSubjectConnector
        calls:
            -   setApplication: [ '@hbpf.application.fakturoid' ]
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
