services:
    _defaults:
        public: '%public.services%'

    hbpf.application.flexibee:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\FlexiBee\FlexiBeeApplication
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@hbpf.application_install.repository'

    hbpf.connector.flexibee.get-contacts-array:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\FlexiBee\Connector\FlexiBeeGetContactsArrayConnector
        calls:
            - setApplication : ['@hbpf.application.flexibee']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.flexibee.create-new-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\FlexiBee\Connector\FlexiBeeCreateNewContactConnector
        calls:
            - setApplication : ['@hbpf.application.flexibee']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]
