services:
    _defaults:
        public: '%public.services%'

    hbpf.application.google-drive:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\GoogleDrive\GoogleDriveApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'

    hbpf.connector.google-drive.upload-file:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\GoogleDrive\Connector\GoogleDriveUploadFileConnector
        calls:
            -   setApplication: [ '@hbpf.application.google-drive' ]
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
