services:
    _defaults:
        public: '%public.services%'

    hbpf.application.hub-spot:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\HubSpotApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'

    hbpf.connector.hub-spot.create-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Connector\HubSpotCreateContactConnector
        calls:
            -   setApplication: [ '@hbpf.application.hub-spot' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
            -   setLogger: [ '@monolog.logger.commons' ]
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.custom_node.hub-spot.create-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Mapper\HubSpotCreateContactMapper
        arguments:
          [ '@hbpf.application_install.repository' ]
