services:
    _defaults:
        public: '%public.services%'

    hbpf.application.hub-spot:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\HubSpotApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'

    hbpf.connector.hub-spot.create-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Connector\HubSpotCreateContactConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.hub-spot']]
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.custom_node.hub-spot.create-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Mapper\HubSpotCreateContactMapper