services:
  _defaults:
    public: '%public.services%'

  hbpf.application.i-doklad:
    class: Hanaboso\HbPFConnectors\Model\Application\Impl\IDoklad\IDokladApplication
    arguments:
      - '@hbpf.providers.oauth2_provider'

  hbpf.connector.i-doklad.new-invoice-recieved:
    class: Hanaboso\HbPFConnectors\Model\Application\Impl\IDoklad\Connector\IDokladNewInvoiceRecievedConnector
    calls:
      -   setApplication: [ '@hbpf.application.i-doklad' ]
      -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
      -   setSender: [ '@hbpf.transport.curl_manager' ]

  hbpf.connector.i-doklad.create-new-contact:
    class: Hanaboso\HbPFConnectors\Model\Application\Impl\IDoklad\Connector\IDokladCreateNewContactConnector
    calls:
      -   setApplication: [ '@hbpf.application.i-doklad' ]
      -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
      -   setSender: [ '@hbpf.transport.curl_manager' ]
