services:
    _defaults:
        public: '%public.services%'

    hbpf.application.nutshell:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Nutshell\NutshellApplication

    hbpf.connector.nutshell-create-contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Nutshell\Connector\NutshellCreateContactConnector
        calls:
            -   setApplication: [ '@hbpf.application.nutshell' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]
