services:
    _defaults:
        public: '%public.services%'

    hbpf.batch.batch-get_application_for_refresh:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\Connector\GetApplicationForRefreshBatchConnector
        arguments:
            - '@hbpf.application_install.repository'

    hbpf.custom_node.refresh_oauth2_token:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\Connector\RefreshOAuth2TokenNode
        arguments:
            - '@hbpf.application.loader'
            - '@hbpf.application_install.repository'
