services:
    _defaults:
        public: '%public.services%'

    hbpf.connector.batch-get_application_for_refresh:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\Connector\GetApplicationForRefreshBatchConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.custom_node.refresh_oauth2_token:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\Connector\RefreshOAuth2TokenNode
        arguments:
            - '@hbpf.application.loader'
        calls:
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
