services:
    _defaults:
        public: '%public.services%'

    hbpf.application.send-grid:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\SendGrid\SendGridApplication

    hbpf.connector.send-grid.send-email:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\SendGrid\Connector\SendGridSendEmailConnector
        calls:
            -   setApplication: [ '@hbpf.application.send-grid' ]
            -   setDb: [ '@doctrine_mongodb.odm.default_document_manager' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
