services:
    _defaults:
        public: '%public.services%'

    hbpf.application.hubspot:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\HubspotApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'
            - '@hbpf.transport.curl_manager'

    hbpf.application.mailchimp:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Mailchimp\MailchimpApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'
            - '@hbpf.transport.curl_manager'

    hbpf.application.shipstation:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\ShipstationApplication

    hbpf.connector.hubspot_create_contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Connector\HubspotCreateContactConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.hubspot']]

    hbpf.connector.mailchimp_create_contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Mailchimp\Connector\MailchimpCreateContactConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.mailchimp']]

    hbpf.connector.shipstation_new_order:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\Connector\ShipstationNewOrderConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.shipstation']]

    hbpf.custom_node.hubspot_create_contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Hubspot\Mapper\HubspotCreateContactMapper

    hbpf.custom_node.mailchimp_create_contact:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Mailchimp\Mapper\MailchimpCreateContactMapper
