services:
    _defaults:
        public: '%public.services%'

    hbpf.custom_node.get_application_for_refresh_batch:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\CustomNode\GetApplicationForRefreshBatch
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.custom_node.refresh_oauth2_token:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\CustomNode\RefreshOAuth2TokenCustomNode
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.loader.application'
