services:
    _defaults:
        public: '%public.services%'

    hbpf.custom_node.get_application_for_refresh_batch:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\CustomNode\GetApplicationForRefreshBatch
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.custom_node.refresh_oauth2_token:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\OAuth2\CustomNode\RefreshOAuth2TokenCustomNode
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@hbpf.application.loader'

    hbpf.application.s3:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\S3Application
        arguments:

    hbpf.connector.s3-create-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\CreateS3ObjectConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication', ['@hbpf.application.s3']]

    hbpf.connector.s3-get-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\GetS3ObjectConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication', ['@hbpf.application.s3']]

    hbpf.connector.s3-delete-object:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\S3\Connector\DeleteS3ObjectConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication', ['@hbpf.application.s3']]

    hbpf.application.redshift:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\Redshift\RedshiftApplication

    hbpf.connector.redshift_execute_query:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\AmazonApps\Redshift\Connector\RedshiftExecuteQueryConnector
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.redshift']]
