services:
    _defaults:
        public: '%public.services%'

    hbpf.application.shipstation:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\ShipstationApplication

    hbpf.connector.shipstation_new_order:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\Connector\ShipstationNewOrderConnector
        calls:
            -   setApplication: [ '@hbpf.application.shipstation' ]
            -   setSender: [ '@hbpf.transport.curl_manager' ]
        arguments:
          [ '@hbpf.application_install.repository' ]
