services:
    _defaults:
        public: '%public.services%'

    hbpf.application.shipstation:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\ShipstationApplication

    hbpf.connector.shipstation_new_order:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shipstation\Connector\ShipstationNewOrderConnector
        arguments:
            - '@hbpf.transport.curl_manager'
            - '@doctrine_mongodb.odm.default_document_manager'
        calls:
            - ['setApplication',['@hbpf.application.shipstation']]