services:
    _defaults:
        public: '%public.services%'

    hbpf.application.shoptet:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\ShoptetApplication
        arguments:
            - '@hbpf.providers.oauth2_provider'
            - '@hbpf.transport.curl_manager'
            - '%startingPointHost%'

    hbpf.connector.shoptet-get-api-access-token:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetGetApiAccessTokenConnector
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.shoptet-updated-order-connector:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetUpdatedOrderConnector
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.shoptet-create-order:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetCreateOrderConnector
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.shoptet-update-order:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetUpdateOrderConnector
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.shoptet-get-eshop-info:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetGetEshopInfo
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]

    hbpf.connector.shoptet-register-webhook:
        class: Hanaboso\HbPFConnectors\Model\Application\Impl\Shoptet\Connector\ShoptetRegisterWebhookConnector
        calls:
            - setApplication : ['@hbpf.application.shoptet']
            - setSender : ['@hbpf.transport.curl_manager']
        arguments:
          [ '@hbpf.application_install.repository' ]
